alienStructureThree = {
    "main": {
        "drawPoints": [
            new Vector(-5, 15),
            new Vector(-5, 10),
            new Vector(-10, 10),
            new Vector(-10, 15),
            new Vector(-15, 15),
            new Vector(-15, 10),
            new Vector(-20, 10),
            new Vector(-20, 0),
            new Vector(-15, 0),
            new Vector(-15, -5),
            new Vector(-10, -5),
            new Vector(-10, -10),
            new Vector(-5, -10),
            new Vector(-5, -15),
            new Vector(5, -15),
            new Vector(5, -10),
            new Vector(10, -10),
            new Vector(10, -5),
            new Vector(15, -5),
            new Vector(15, 0),
            new Vector(20, 0),
            new Vector(20, 10),
            new Vector(15, 10),
            new Vector(15, 15),
            new Vector(10, 15),
            new Vector(10, 10),
            new Vector(5, 10),
            new Vector(5, 15),
            new Vector(-5, 15),
        ],
        "fillColour": "#ffffff",
        "strokeColour": ""
    },
    "left_eye": {
        "drawPoints": [
            new Vector(-10, 0),
            new Vector(-5, 0),
            new Vector(-5, 5),
            new Vector(-10, 5),
            new Vector(-10, 0),
        ],
        "fillColour": "#000000",
        "strokeColour": "",
    },
    "right_eye": {
        "drawPoints": [
            new Vector(5, 0),
            new Vector(10, 0),
            new Vector(10, 5),
            new Vector(5, 5),
            new Vector(5, 0),
        ],
        "fillColour": "#000000",
        "strokeColour": "",
    },
    "left_square_1": {
        "drawPoints": [
            new Vector(-15, 15),
            new Vector(-20, 15),
            new Vector(-20, 20),
            new Vector(-15, 20),
            new Vector(-15, 15),
        ],
        "fillColour": "#ffffff",
        "strokeColour": "",
    },
    "left_square_2": {
        "drawPoints": [
            new Vector(-15, 20),
            new Vector(-10, 20),
            new Vector(-10, 25),
            new Vector(-15, 25),
            new Vector(-15, 20),
        ],
        "fillColour": "#ffffff",
        "strokeColour": "",
    },
    "right_square_1": {
        "drawPoints": [
            new Vector(15, 15),
            new Vector(20, 15),
            new Vector(20, 20),
            new Vector(15, 20),
            new Vector(15, 15),
        ],
        "fillColour": "#ffffff",
        "strokeColour": "",
    },
    "right_square_2": {
        "drawPoints": [
            new Vector(15, 20),
            new Vector(10, 20),
            new Vector(10, 25),
            new Vector(15, 25),
            new Vector(15, 20),
        ],
        "fillColour": "#ffffff",
        "strokeColour": "",
    },
}