const alienStructureOne = {
    "main": {
        "drawPoints": [
            new Vector(-10, 25),
            new Vector(-10, 30),
            new Vector(-20, 30),
            new Vector(-20, 25),
            new Vector(-25, 25),
            new Vector(-25, 20),
            new Vector(-20, 20),
            new Vector(-20, 15),
            new Vector(-30, 15),
            new Vector(-30, 0),
            new Vector(-25, 0),
            new Vector(-25, -5),
            new Vector(-10, -5),
            new Vector(-10, -10),
            new Vector(10, -10),
            new Vector(10, -5),
            new Vector(25, -5),
            new Vector(25, 0),
            new Vector(30, 0),
            new Vector(30, 15),
            new Vector(20, 15),
            new Vector(20, 20),
            new Vector(25, 20),
            new Vector(25, 25),
            new Vector(20, 25),
            new Vector(20, 30),
            new Vector(10, 30),
            new Vector(10, 25),
            new Vector(15, 25),
            new Vector(15, 20),
            new Vector(5, 20),
            new Vector(5, 25),
            new Vector(-5, 25),
            new Vector(-5, 20),
            new Vector(-15, 20),
            new Vector(-15, 25),
            new Vector(-10, 25),
        ],
        "fillColour": "#ffffff",
    },
    "left eye": {
        "drawPoints": [
            new Vector(-15, 5),
            new Vector(-5, 5),
            new Vector(-5, 10),
            new Vector(-15, 10),
            new Vector(-15, 5),],
        "fillColour": "#000000",
        "strokeColour": "",
    },
    "right eye": {
        "drawPoints": [
            new Vector(15, 5),
            new Vector(5, 5),
            new Vector(5, 10),
            new Vector(15, 10),
            new Vector(15, 5),],
        "fillColour": "#000000",
        "strokeColour": "",
    },
    "mouth": {
        "drawPoints": [
            new Vector(-5, 15),
            new Vector(5, 15),
            new Vector(5, 20),
            new Vector(-5, 20),
            new Vector(-5, 15),],
        "fillColour": "#000000",
        "strokeColour": "",
    }
}